[env:esp32wroom]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = default.csv

[env:esp32wroom_ota]
extends = env:esp32wroom
upload_protocol = espota
upload_port = aegis-wroom.local
upload_flags =
    --auth=vanitas
